name: Bot
on:
  push:
    branches:
      - master

jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  readme:
    name: Update README
    runs-on: ubuntu-latest
    needs: cancel
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3

      - run: |
          haxe --cwd extra/readme build-github.hxml
          git config --local user.name "[bot]"
          git config --local user.email ""
          git commit --allow-empty -m "update readme" README.md

      - uses: ad-m/github-push-action@master
        if: ${{ env.ECSO_README_CHANGED == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}